Contents
knalin55/NPFL128-LTIP pull request #1
Opened 2022-08-29 18:39 UTC by knalin55

2022-09-11 19:10 UTC, jirka-x1 requested changes

2022-09-11 19:10 UTC, jirka-x1 commented on data/make_parquet.py
> +    with open('{}.csv'.format(args.language), "w") as file:
The f-strings are now typically preferred over using `format`.
```suggestion
    with open(f'{args.language}.csv', "w") as file:
```

2022-09-11 19:10 UTC, jirka-x1 commented on data/make_parquet.py
> +                    file.write(str(count) + "\t" + line.strip("\n") + " \n")
Either make sure `line` does not contains `\t` or (preferably) use `csvreader` (with \t as the separator)

2022-09-11 19:10 UTC, jirka-x1 commented on data/make_parquet.py
> +# Write first args.num_lines to a csv file.
Is it csv or tsv? And you use txt ending.

2022-09-11 19:10 UTC, jirka-x1 commented on evaluate.py
> +def main(args: argparse.Namespace) -> None:
split into well defined functions (here and all other places)

2022-09-11 19:10 UTC, jirka-x1 commented on evaluate.py
> +
In several places, you have these random empty lines. Follow PEP8. Doesn't your IDE complain?

2022-09-11 19:10 UTC, jirka-x1 commented on evaluate.py
> +        triples_list    = []
You do not explain what are triples.

2022-09-11 19:10 UTC, jirka-x1 commented on evaluate.py
> +                label = label + sub + " ".join(triple.split("|")[0].strip().split("_")) \
this is too hard to read; add a comment.
Also you could create a (commented) function for doing
```
def some_intuitive_name(text: str, some_intuitive_name_for_triple_index: int) -> str:
    return text.split("|")[some_intuitive_name_for_triple_index].strip().split("_")
```

2022-09-11 19:10 UTC, jirka-x1 commented on pretrain.py
> +            ru.append(line.split("\t")[1])
why not:
```suggestion
        en = [line.split("\t")[0] for line in dataset]
        ru = [line.split("\t")[1] for line in dataset]
```
But again, you should create a function for getting n-th column from a dataset.

2022-09-11 19:10 UTC, jirka-x1 commented on finetune.py
> +    main(args)
Make sure all files contain `\n` as the last character (See 4.6 https://ufal.mff.cuni.cz/courses/npfl096-2014-su/project)

2022-09-11 19:10 UTC, jirka-x1 commented on pretrain.py
> +def main(args: argparse.Namespace) -> None:
split into functions

2022-09-18 20:03 UTC, knalin55 commented on evaluate.py
> +
My MS VS Code had a different linter selected as default. So it didn't show the coding style-related issues. I have fixed the scripts now. It should be better than before.

2022-09-21 11:42 UTC, jirka-x1 requested changes

2022-09-21 11:42 UTC, jirka-x1 commented on data/make_parquet.py
>          with open(os.path.join(args.directory, '{}.txt'.format(args.language))) as r_file:
You changed the formatting to "f" string above (for the output file), but not here.

2022-09-21 11:42 UTC, jirka-x1 commented on data/make_parquet.py
> +    df = pd.read_csv('{}.tsv'.format(args.language), sep="\t")
ditto (and elsewhere)

2022-09-21 11:42 UTC, jirka-x1 commented on evaluate.py
> +    def extract_component(triple: str, entity_index: int) -> str:
why is this a function under main? (the disadvantage is that you can access any variables in main (langs, args, prefix). 
Make it a normal function (and similarly the other ones)

2022-09-21 11:42 UTC, jirka-x1 commented on evaluate.py
> +    def preprocess_data(lang):
what is the type of lang? All basic function arguments should have a type hint (exceptions are complex objects from third party untyped libraries, where it is not easy to find out what the type is)

2022-09-21 11:42 UTC, jirka-x1 commented on pretrain.py
> +        dataset = open("./data/news-commentary-v14.en-ru.tsv").read().split("\n")
yes, but obviously using a CsvReader (with \t as separator) is recommended.

2023-08-07 08:22 UTC, merged